version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  archivist:
    container_name: archivist
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      MONGO_DOMAIN: "mongo:27017"
      MONGO_DATABASE: local
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
